<a href="https://colab.research.google.com/github/mhrznamrit/dsml_batch_12/blob/main/Day29_Eigen_SVD_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [1,2],
    [3,4]
])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigen values: ", eigenvalues)
print("Eigen vector:\n ", eigenvectors)

Eigen values:  [-0.37228132  5.37228132]
Eigen vector:
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [ ]:
U, S, V = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", S)
print("V matrix:\n", V)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Sigma values: [5.4649857  0.36596619]
V matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

In [ ]:
print(U @ U.T)

[[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]

# Pandas

In [ ]:
import pandas as pd

In [ ]:
a = ['g', 'e', 'f', 's']
res = pd.Series(a)
print(res)

0     g
1     e
2     f
3     s
4    10
dtype: object

In [ ]:
sample = {"Country":"Nepal", "Capital":"Kathmandu", "Population":"3 crore", "Area": 147181}
result = pd.Series(sample)
print(result)

Country           Nepal
Capital       Kathmandu
Population      3 crore
Area             147181
dtype: object

In [ ]:
res_data = pd.DataFrame(result, columns=["Details"])
print(res_data)

              Details
Country         Nepal
Capital     Kathmandu
Population    3 crore
Area           147181

In [ ]:
res_data['Details']

Country           Nepal
Capital       Kathmandu
Population      3 crore
Area             147181
Name: Details, dtype: object

In [ ]:
data = {
    "Name": ["Defoe", "J. Terry", "Lampard"],
    "Team": ["Newcastle", "Chelsea", "Chelsea"],
    "Number": [23, 5, 22],
    "Age": [33, 38, 31]
}
tab = pd.DataFrame(data)
print(tab)

       Name       Team  Number  Age
0     Defoe  Newcastle      23   33
1  J. Terry    Chelsea       5   38
2   Lampard    Chelsea      22   31

In [ ]:
tab[['Name','Team']]

       Name       Team
0     Defoe  Newcastle
1  J. Terry    Chelsea
2   Lampard    Chelsea

In [ ]:
tab[['Name','Team','Age']]

       Name       Team  Age
0     Defoe  Newcastle   33
1  J. Terry    Chelsea   38
2   Lampard    Chelsea   31

In [ ]:
res = tab.loc[tab['Name']=='Lampard']
res

      Name     Team  Number  Age
2  Lampard  Chelsea      22   31

In [ ]:
tab.to_csv("data.csv", index=False)

In [ ]:
df = pd.read_csv("data.csv")
df

       Name       Team  Number  Age
0     Defoe  Newcastle      23   33
1  J. Terry    Chelsea       5   38
2   Lampard    Chelsea      22   31

In [ ]:
a = {
    'Name': ['Jai','Princi','Gaurav','Anuj'],
    'Age': [27, 24, 22, 32],
    'Address': ['Delhi','Kanpur','Allahabad','Kannauj'],
    'Qualification': ['Msc','MA','MCA','Phd']
}
df = pd.DataFrame(a)
print(df[['Name','Qualification']])

     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd

In [ ]:
print(df['Name'])
print(df[['Name','Address']])

0       Jai
1    Princi
2    Gaurav
3      Anuj
Name: Name, dtype: object
     Name    Address
0     Jai      Delhi
1  Princi     Kanpur
2  Gaurav  Allahabad
3    Anuj    Kannauj

In [ ]:
a = {
 'Name': ['Mohe', 'Shyni', 'Parul', 'Sam'],
 'ID': [12, 43, 54, 32],
 'City': ['Delhi', 'Kochi', 'Pune', 'Patna']
}
df = pd.DataFrame(a)
res = df.loc[df['Name'] == 'Mohe']
print(res)

   Name  ID   City
0  Mohe  12  Delhi